baseURL = "https://satish28.github.io/Blog"
languageCode = "en-us"
title = "Satish S"
theme = "noteworthy"
publishDir = "docs/"
paginate = 3
summaryLength = 10
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
enableEmoji = true

[taxonomies]
  tag = "tags"

[params]

	# Main

    twitter = "https://twitter.com/satish28888"
	linkedin = "https://www.linkedin.com/in/satish-s-52261a8b/"

    # Running
    strava = "#"

	# Programming
    github = "https://github.com/satish28/"


# Menu links along the sidebar navigation.


[[menu.main]]
	name = "Running"
	identifier = "Running"
	url = "running/"
	weight = 1

[[menu.main]]
	name = "reverseengg"
	identifier = "reverseengg"
	url = "reverseengg/"
	weight = 2


[[menu.main]]
	identifier = "tags"
	name = "Tags"
	url = "tags/"
	weight = 3

[[menu.main]]
	identifier = "about"
	name = "About"
	url = "about/"
	weight = 4

[[menu.main]]
	identifier = "archives"
	name = "archives"
	url = "archives/"
	weight = 5
