baseURL = "https://www.satish28.github.io/Blog/"
languageCode = "en-us"
title = "Satish S"
theme = "Erblog"
publishDir = "docs/"
paginate = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
